###############################
##### COMMUNITY PAGE MENU #####
###############################
[[docs]]
  name = "About Us"
  weight = 10
  identifier = "about"
  url = "/community/about/"
  
[[docs]]
  name = "Help & Guides"
  weight = 20
  identifier = "help"
  url = "/community/help/"
###############################
##### COMMUNITY PAGE MENU #####
###############################


###############################
##### MAIN LEFT NAV MENU #####
###############################
[[main]]
  name = "Community"
  url = "/community/about/our-story/"
  weight = 50

[[main]]
  name = "Playbook"
  url = "/playbook/introduction/"
  weight = 20

[[main]]
  name = "Products"
  url = "/products/open-sourced/"
  weight = 30

[[main]]
  name = "Stories"
  url = "/stories/"
  weight = 40
###############################
##### MAIN LEFT NAV MENU #####
###############################


###############################
##### MAIN RIGHT NAV MENU #####
###############################
# [[social]]
#   name = "Twitter"
#   pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
#   url = "https://twitter.com/gethyas"
#   weight = 10


# [[social]]
#   name = "Sponsor"
#   pre = "SPONSOR"
#   url = "https://butterops.slack.com"
#   weight = 30

[[social]]
  name = "Slack"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-slack\"><path d=\"M14.5 10c-.83 0-1.5-.67-1.5-1.5v-5c0-.83.67-1.5 1.5-1.5s1.5.67 1.5 1.5v5c0 .83-.67 1.5-1.5 1.5z\"></path><path d=\"M20.5 10H19V8.5c0-.83.67-1.5 1.5-1.5s1.5.67 1.5 1.5-.67 1.5-1.5 1.5z\"></path><path d=\"M9.5 14c.83 0 1.5.67 1.5 1.5v5c0 .83-.67 1.5-1.5 1.5S8 21.33 8 20.5v-5c0-.83.67-1.5 1.5-1.5z\"></path><path d=\"M3.5 14H5v1.5c0 .83-.67 1.5-1.5 1.5S2 16.33 2 15.5 2.67 14 3.5 14z\"></path><path d=\"M14 14.5c0-.83.67-1.5 1.5-1.5h5c.83 0 1.5.67 1.5 1.5s-.67 1.5-1.5 1.5h-5c-.83 0-1.5-.67-1.5-1.5z\"></path><path d=\"M15.5 19H14v1.5c0 .83.67 1.5 1.5 1.5s1.5-.67 1.5-1.5-.67-1.5-1.5-1.5z\"></path><path d=\"M10 9.5C10 8.67 9.33 8 8.5 8h-5C2.67 8 2 8.67 2 9.5S2.67 11 3.5 11h5c.83 0 1.5-.67 1.5-1.5z\"></path><path d=\"M8.5 5H10V3.5C10 2.67 9.33 2 8.5 2S7 2.67 7 3.5 7.67 5 8.5 5z\"></path></svg>"
  url = "https://butterops.slack.com"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/butterops"
  post = "v0.1.0"
  weight = 20
###############################
##### MAIN RIGHT NAV MENU #####
###############################

###############################
##### FOOTER MENU #####
###############################
[[footer]]
  name = "Privacy"
  url = "/privacy-policy/"
  weight = 10

[[footer]]
  name = "Code of Conduct"
  url = "/code-of-conduct/"
  weight = 20

[[footer]]
  name = "Contributors"
  url = "/contributors"
  weight = 30
###############################
##### FOOTER MENU #####
###############################


###############################
##### PLAYBOOK PAGE MENU #####
###############################
[[tutorial]]
  name = "Prologue"
  weight = 10
  identifier = "prologue"
  url = "/playbook/introduction"

[[tutorial]]
  name = "1. Create Your MVP"
  weight = 20
  identifier = "playbook"
  url = "/playbook/developer-guide"

[[tutorial]]
  name = "2. Grow your Audience"
  weight = 30
  identifier = "opensource"
  url = "/playbook/open-source-guide"
  # Start os, build community, Maintain, Govern

[[tutorial]]
  name = "3. Sustain Development and Operations"
  weight = 40
  identifier = "operations"
  url = "/playbook/operations"
  # legal, revenue and users
###############################
##### PLAYBOOK PAGE MENU #####
###############################

###############################
##### PRODUCTS PAGE MENU #####
###############################
[[showcase]]
  name = "Browse"
  weight = 20
  identifier = "browse"
  url = "/products/browse"

[[showcase]]
  name = "Contribute / Try"
  weight = 10
  identifier = "try"
  url = "products/try/"
###############################
##### PRODUCTS PAGE MENU #####
###############################
