# Meta Data for SEO

## Homepage
title = "ButterOps Dev"
titleSeparator = "-"
titleAddition = "Promoting Social Entrepreneurship"
description = "ButterOps Dev Community is a free and open organization headquartered in Bengaluru, India. I @mrdotkg, brought this multi disciplinary software team together in early 2020. Our founding team includes experts in Product / SaaS Development. Grow your - online service | side projects | software skills."

## Open Graph + Twitter Cards
images = [""]
twitterSite = "henkverlinde"
twitterCreator = "henkverlinde"
facebookAuthor = "verlinde.henk"
facebookPublisher = "verlinde.henk"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo.png"
schemaTwitter = "https://twitter.com/henkverlinde"
schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaGitHub = "https://github.com/h-enk"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Our mission is to encourage and empower social entrepreneurship among developers for free. We accomplish this by creating quality tools, articles and starting up guides - all freely available to the public."

# Alert
alert = false
alertText = "Released <a target=\"blank\" class=\"alert-link\" href=\"https://chrome.google.com/webstore/detail/refer-web-clipper/ijklgagbolpfgfjkclcgcepdbiopnikh?hl=en\">Refer Ext.</a> into marketplace."

# Edit Page
docsRepo = "https://github.com/butterops/butterops.dev"
editPage = true
