[build]
  publish = "public"
  functions = "functions"

[build.environment]
  HUGO_VERSION = "0.80.0"
  NODE_VERSION = "15.5.1"
  NPM_VERSION = "7.3.0"

[context.production]
  command = "hugo --gc --minify && npm run build:functions"

[context.deploy-preview]
  command = "hugo --gc --minify"

[context.branch-deploy]
  command = "hugo --gc --minify"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
    sitemapPath = "/sitemap.xml"
    providers = [
      "google",
      "bing",
      "yandex"
    ]

[[redirects]]
  from = "/playbook/"
  to = "/playbook/introduction/"
  status = 301
  force = false

[[redirects]]
  from = "/products/"
  to = "/products/glimpse/"
  status = 301
  force = false

[[redirects]]
  from = "/community/"
  to = "/community/our-story/"
  status = 301
  force = false

[[redirects]]
  from = "/about/"
  to = "/community/our-story/"
  status = 301
  force = false
